<?php

namespace App\Controller;

use App\Repository\PostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class PostController extends AbstractController
{
    #[Route('/createPosts', name: 'posts', methods: ['POST','GET'])]
    public function createForm(string $type, mixed $data = null, array $options = []): FormInterface
    {
        $post = new Post();
        $post->setTitle('Title');
        $post->setContent('Content');
        $post->setCreatedAt(new \DateTime('now'));
        $post->setUpdatedAt(new \DateTime('now'));

        return parent::createForm($type, $data, $options); // TODO: Change the autogenerated stub
    }
}