controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#default_home:
#    path: /
#    controller: App\Controller\DefaultController::home

#default_contact:
#    path: /contact
#    controller: App\Controller\DefaultController::contact